title: "Entries"
author: "clxrity"
description: "we'll manage"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home", icon: <i class="fa-solid fa-house"></i>}
  - {file: "home.html", title: "Entries", icon: <i class="fa-solid fa-image-portrait"></i>}
  - {file: "submit.html", title: "Submit", icon: <i class="fa-solid fa-inbox"></i>}
  - {url: "https://clxrity.xyz", title: "clxrity", icon: <i class="fa-solid fa-globe"></i>}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: GitHub, icon: github, url: "https://github.com/clxrityy/posts"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/yourclxrity"}
  - {title: Instagram, icon: instagram, url: "https://instagram.com/mjxnglin"}
  - {title: SoundCloud, icon: soundcloud, url: "https://soundcloud.com/clxrityy"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
