title: "Entries"
author: "clxrity"
description: "we'll manage"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "home.html", title: "Entries"}
  - {file: "index.md", title: "Home"}
  - {file: "submit.html", title: "Submit"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Instagram, icon: instagram, url: "https://instagram.com/mjxnglin"}
  - {title: Github, icon: github, url: "https://github.com/clxrityy/posts"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/yourclxrity"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
